In [1]:
import numpy as np
import pandas as pd

In [2]:
x = pd.read_csv('x.csv')
y = pd.read_csv('y.csv')

In [7]:
x = x.drop(columns='518')

In [8]:
y = y.drop(columns='Unnamed: 0')

In [24]:
temp = pd.DataFrame()
temp=temp.append([2527])
for i in range(len(x)):
    temp=temp.append([x['2527.0'][i]])

In [25]:
temp

          0
0    2527.0
0    2209.0
0    1910.0
0    1668.0
0    1474.0
0    1127.0
0     773.0
0     610.0
0     527.0
0     384.0
0     308.0
0     226.0
0     194.0
0     178.0
0     152.0
0     121.0
0     129.0
0      99.0
0      86.0
0      73.0
0      73.0
0      93.0
0      81.0
0      98.0
0     100.0
0     139.0
0     148.0
0     198.0
0     167.0
0     202.0
..      ...
0     189.0
0     166.0
0     173.0
0     210.0
0     363.0
0     366.0
0     332.0
0     415.0
0     476.0
0     260.0
0     327.0
0     359.0
0     555.0
0     777.0
0    1489.0
0    2124.0
0    3479.0
0    3870.0
0    4885.0
0    7250.0
0   12246.0
0   17213.0
0   15264.0
0   13977.0
0   15674.0
0   17777.0
0   21202.0
0   20931.0
0   19454.0
0   11249.0

[259 rows x 1 columns]

In [33]:
x2 = np.array(temp).reshape(1,-1)

In [34]:
np.polyfit(x2,y,1)

TypeError: expected 1D vector for x

In [37]:
y.shape

(259, 1)